### ISSUE TITLE
Would like to override HTML_DIR

### ISSUE THREAD

**Issue by mradcliffe** [wodby/apache#1]
I would like to override HTML_DIR in my own instance of docker4drupal docker-compose.yml so that I can use my preferred directory structure without creating a derivative image

I am able to add the following, but because the directory does not exist the container won't start. I think this is the correct repository issue queue to add this issue to because HTML_DIR is defined in wodby/apache.

```yaml
apache:
  image: wodby/drupal-apache:2.4-1.0.2
  depends_on:
    - php
  environment:
    APACHE_LOG_LEVEL: debug
    APACHE_BACKEND_HOST: php
    APACHE_SERVER_ROOT: "/var/www/not-html"
    HTML_DIR: "/var/www/not-html"
```

```
apache_1      | chown: /var/www/not-html: No such file or directory
apache_1      | chown: /var/www/not-html: No such file or directory
name_apache_1 exited with code 1
```

Would it be possible to add `mkdir -p ${HTML_DIR}` into Dockerfile?
